# yaml-language-server: $schema=../.schema/databricks.json
resources:
  jobs:
    training_agent_job:
      name: general_agent_training
      description: |
        General Agent Training Job
      tags:
        environment: ${bundle.target}
      max_concurrent_runs: 1
      tasks:
        - task_key: training
          description: |
            Agent Training Script
          spark_python_task:
            python_file: ../src/agent_train.py
            parameters:
              - "--model_name"
              - "${var.general_agent_model_name}"
          libraries:
            - whl: ../dist/*.whl
          new_cluster:
            instance_pool_id: ${var.instance_pool_id}
            spark_version: 16.4.x-scala2.12
            is_single_node: true
            spark_conf:
              spark.databricks.cluster.profile: singleNode
              spark.master: local[*]
            spark_env_vars:
              AZURE_OPENAI_API_KEY: "{{secrets/nonprodgaalabkv/nonprodgaalaboai-apikey}}"
              AZURE_OPENAI_ENDPOINT: https://nonprodgaalaboai.openai.azure.com/
              OPENAI_API_VERSION: 2024-12-01-preview
              MLFLOW_EXPERIMENT_ID: ${resources.experiments.general_agent_experiment.id}
            custom_tags:
              ResourceClass: SingleNode
            kind: CLASSIC_PREVIEW
            use_ml_runtime: true
